# Point hfagent at Hugging Face on Windows.
#
#   powershell -ExecutionPolicy Bypass -File scripts\setup-huggingface.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\setup-huggingface.ps1 -Gpu -Yes

[CmdletBinding()]
param(
    [string]$Repo = "Qwen/Qwen2.5-Coder-7B-Instruct",
    [string]$Name = "hfagent-coder",
    [switch]$Gpu,
    [switch]$Yes
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

function Write-Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message"
}

if (-not (Get-Command hf -ErrorAction SilentlyContinue)) {
    throw "This script is for the Hugging Face cloud, not local Ollama. For Ollama run: powershell -ExecutionPolicy Bypass -File .\scripts\configure-ollama.ps1"
}

try {
    hf auth whoami --format quiet | Out-Null
} catch {
    Write-Step "Not logged in. A browser window will open."
    hf auth login --add-to-git-credential
}

$Token = (hf auth token).Trim()
if (-not $Token) {
    throw "Could not read the access token. Create one at https://huggingface.co/settings/tokens"
}

$ProfileDir = Join-Path $HOME ".hfagent"
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
$EnvFile = Join-Path $ProfileDir "hf.env.ps1"
@"
# Generated by scripts/setup-huggingface.ps1
`$env:HF_TOKEN = '$Token'
`$env:HF_BASE_URL = 'https://router.huggingface.co/v1'
`$env:HFAGENT_MODEL = '$Repo'
"@ | Set-Content -Path $EnvFile

Write-Step "Serverless router is ready (pay per request, no dedicated GPU)."
Write-Host "  . $EnvFile"
Write-Host "  $Root\.venv\Scripts\hfagent.exe --model $Repo"

if (-not $Gpu) {
    Write-Host ""
    Write-Host "To rent a dedicated GPU later (hourly billing until you pause/delete it):"
    Write-Host "  .\scripts\setup-huggingface.ps1 -Gpu -Yes"
    Write-Host "  hf endpoints pause $Name"
    Write-Host "  hf endpoints delete $Name --yes"
    exit 0
}

if (-not $Yes) {
    throw "Dedicated GPUs are billed while running. Re-run with -Gpu -Yes to confirm."
}

Write-Step "Deploying catalog endpoint $Name from $Repo"
hf endpoints catalog deploy --repo $Repo --name $Name --accelerator gpu

Write-Step "Endpoint requested."
Write-Host "  hf endpoints describe $Name"
Write-Host "Stop billing:  hf endpoints pause $Name"
