#!/usr/bin/env bash
# Point hfagent at Hugging Face: login, then the serverless router
# (default) or a dedicated GPU Inference Endpoint (--gpu).
#
#   ./scripts/setup-huggingface.sh
#   ./scripts/setup-huggingface.sh --gpu
#   ./scripts/setup-huggingface.sh --gpu --repo Qwen/Qwen2.5-Coder-7B-Instruct
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="Qwen/Qwen2.5-Coder-7B-Instruct"
NAME="hfagent-coder"
WANT_GPU=0
CONFIRM_GPU=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gpu) WANT_GPU=1; shift ;;
    --yes) CONFIRM_GPU=1; shift ;;
    --repo) REPO="${2:?}"; shift 2 ;;
    --name) NAME="${2:?}"; shift 2 ;;
    -h|--help)
      cat <<'HELP'
Set up hfagent on Hugging Face.

  ./scripts/setup-huggingface.sh              # login + serverless router
  ./scripts/setup-huggingface.sh --gpu --yes  # also rent a dedicated GPU
                                              # (billed while the endpoint is up)

  --repo Qwen/Qwen2.5-Coder-7B-Instruct
  --name hfagent-coder
HELP
      exit 0
      ;;
    *)
      echo "unknown flag: $1" >&2
      exit 2
      ;;
  esac
done

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
log() { printf '\n==> %s\n' "$*"; }

command -v hf >/dev/null 2>&1 || die "Install the Hub CLI first: curl -LsSf https://hf.co/cli/install.sh | bash"

if ! hf auth whoami --format quiet >/dev/null 2>&1; then
  log "Not logged in. A browser window will open."
  hf auth login --add-to-git-credential
fi

USER_JSON="$(hf auth whoami --format json 2>/dev/null || true)"
echo "$USER_JSON" | grep -q '"name"' || die "Login failed. Get a token at https://huggingface.co/settings/tokens then: hf auth login"

TOKEN="$(hf auth token 2>/dev/null || true)"
[[ -n "$TOKEN" ]] || die "Could not read the access token. Create one at https://huggingface.co/settings/tokens"

PROFILE="$HOME/.hfagent/hf.env"
mkdir -p "$(dirname "$PROFILE")"
cat >"$PROFILE" <<EOF
# Generated by scripts/setup-huggingface.sh
export HF_TOKEN=$TOKEN
export HF_BASE_URL=https://router.huggingface.co/v1
export HFAGENT_MODEL=$REPO
EOF

log "Serverless router is ready (pay per request, no dedicated GPU)."
echo "  source $PROFILE"
echo "  $ROOT/.venv/bin/hfagent --model $REPO"

if [[ "$WANT_GPU" -eq 0 ]]; then
  cat <<EOF

To rent a dedicated GPU later (hourly billing until you pause/delete it):
  $0 --gpu --yes --repo $REPO
  hf endpoints list
  hf endpoints pause $NAME
  hf endpoints delete $NAME --yes
EOF
  exit 0
fi

if [[ "$CONFIRM_GPU" -eq 0 ]]; then
  die "Dedicated GPUs are billed while running. Re-run with --gpu --yes to confirm."
fi

log "Deploying catalog endpoint $NAME from $REPO (this can take several minutes)"
hf endpoints catalog deploy --repo "$REPO" --name "$NAME" --accelerator gpu

log "Endpoint requested. Check status with:"
echo "  hf endpoints describe $NAME"
echo "  hf endpoints list"
echo
echo "When status is running, point hfagent at the endpoint URL from 'describe',"
echo "or keep using the router above (it already routes to HF GPUs)."
echo
echo "Stop billing:"
echo "  hf endpoints pause $NAME"
echo "  hf endpoints delete $NAME --yes"
